baseURL = "https://xiaotianxt.github.io/proj/"
languageCode = "en-us"
title = "NUMA Simulator Project"
theme = "PaperMod"

[params]
  description = "A NUMA simulator (15-418 project)"
  author = "Helen Wang, Yupei Tian"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  TocOpen = true

[params.homeInfoParams]
  Title = "NUMA Simulator"
  Content = """
  A project exploring Non-uniform memory access (NUMA) architecture through simulation.
  
  We are implementing a NUMA simulator to measure memory access latency under different interconnect network policies and page assignments.
  """

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/xiaotianxt/15418-proj"

[menu]
  [[menu.main]]
    identifier = "proposal"
    name = "Project Proposal"
    url = "/proposal/"
    weight = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
